Add dockerize.
Add gitea.

Keep only "latest" version.

Normalize scripts.

Normalize result.

Remove atom.

Remove bootstrap.

Remove cakebox.

Remove docker-ce.

Remove docker-clean.

Remove docker-compose.

Remove drive.

Remove fabric.

Remove homebank.

Remove license.

Remove mailcatcher.

Remove npm-proxy-cache.

Remove php-cs-fixer.

Remove pygitup.

Remove sshuttle.

Remove storm.

Remove vsftpd.

Update README.

diff --git a/bin/generate b/bin/generate
--- a/bin/generate
+++ b/bin/generate
@@ -1,38 +1,49 @@
-#!/bin/sh
-set -e
-cd "$(dirname "$0")/.."
+#!/bin/bash
+set -e -u
+cd "$(dirname "$0")"/..
 
-run() {
-    local RETURN=""
-    local TRY=0
+# Check environment
 
-    echo "[RUN] ${FILE}"
-
-    until [ "${TRY}" -ge 3 ] ; do
-        echo -n "$(cd "$1" && melody run "$2")"
-
-        RETURN="$(ls "$1")"
-        if [ -n "${RETURN}" ] ; then
-            echo "[OK] ${FILE}"
-            break
-        fi
-
-        echo ""
-        TRY="$((${TRY} + 1))"
-        sleep 5
-    done
-
-    if [ "${TRY}" -ge 3 ] ; then
-        echo "[NOK] ${FILE}" >&2
-        exit 1
-    fi
+fail() {
+    echo 1>&2 "$1"
+    echo 1>&2 "Usage: $(basename "$0") [SCRIPT]"
+    exit 255
 }
 
-rm -f -r generated/*
-for FILE in $(find "${PWD}/src" -name "*.php") ; do
-    FOLDER="$(echo "${FILE}" | sed 's@.php$@@')"
-    FOLDER="$(echo "${FOLDER}" | sed 's@/src/@/generated/@')"
-    mkdir -p "${FOLDER}"
+if [ "$#" -lt 1 ]; then
+    fail "Invalid number of arguments."
+fi
 
-    run "${FOLDER}" "${FILE}"
+if [ ! -f "$1" ]; then
+    fail "Script \"$1\" does not exist."
+fi
+
+# Run generator
+
+FILE="$(realpath "$1")"
+FOLDER="$(realpath "$1" | sed "s@/src/@/generated/@" | sed "s@.php\$@@")"
+RETURN=""
+TRY=0
+
+rm -f -r "${FOLDER}"
+mkdir -p "${FOLDER}"
+
+echo "[RUN] ${FILE}"
+
+until [ "${TRY}" -ge 3 ]; do
+    echo -n "$(cd "${FOLDER}" && melody run "${FILE}")"
+
+    RETURN="$(ls "${FOLDER}")"
+    if [ -n "${RETURN}" ]; then
+        echo "[OK] ${FILE}"
+        break
+    fi
+
+    echo 1>&2 "[NOK] ${FILE}"
+    TRY="$((TRY + 1))"
+    sleep 5
 done
+
+if [ "${TRY}" -ge 3 ]; then
+    exit 255
+fi
